version: "3.7"

services:
  userrolesdb:
    image: postgres:18.1@sha256:38d5c9d522037d8bf0864c9068e4df2f8a60127c6489ab06f98fdeda535560f9
    container_name: userrolesdb
    ports:
      - "127.0.0.1:10101:5432"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=userrolesdb
