version: "3.7"

services:
  userrolesdb:
    image: postgres:18.1@sha256:5773fe724c49c42a7a9ca70202e11e1dff21fb7235b335a73f39297d200b73a2
    container_name: userrolesdb
    ports:
      - "127.0.0.1:10101:5432"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=userrolesdb
